
package com.posidex.lifeasia.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ClientMerge", targetNamespace = "http://KLI_ESB.LAServices/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ClientMerge {


    /**
     * 
     * @param part
     * @return
     *     returns com.posidex.stub.ClientMergeESBResponse
     */
    @WebMethod(operationName = "ClientMerge", action = "ClientMerge")
    @WebResult(name = "ClientMergeESBResponse", targetNamespace = "http://KLI.ESB.LA.ClientMerge.Schemas.ClientMerge_ESB_Resp", partName = "part")
    public ClientMergeESBResponse clientMerge(
        @WebParam(name = "ClientMergeESBRequest", targetNamespace = "http://KLI.ESB.LA.ClientMerge.Schemas.ClientMerge_ESB_Req", partName = "part")
        ClientMergeESBRequest part);

}
